// blocketTypes.ts
// Typer för bil + Blocket-sync, anpassade för Supabase/Lovable Cloud databas
// Strukturer enligt Pro Import API v3 OpenAPI-spec (Car category 1020)

export type Car = {
  id: string;
  company_id: string;
  user_id: string;
  make: string;
  model: string;
  year: number;
  mileage: number | null;
  fuel: string | null;
  gearbox: string | null;
  price: number | null;
  description: string | null;
  notes: string | null;
  registration_number: string | null;
  vin: string | null;
  color: string | null;
  image_urls: string[];
  publish_on_blocket: boolean;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};

export type BlocketAdSync = {
  car_id: string;
  source_id: string;
  blocket_ad_id: string | null;
  blocket_store_id: string | null;
  state: "created" | "deleted" | "none";
  last_action: "create" | "update" | "delete" | "bump" | null;
  last_action_state: "processing" | "done" | "error" | null;
  last_error: string | null;
  last_synced_at: string | null;
  created_at: string;
  updated_at: string;
};

// ---- Blocket Pro Import API v3 - Car (category 1020) ----

export type BlocketFuel =
  | "gasoline"
  | "diesel"
  | "electric"
  | "ethanol"
  | "natural_gas";

export type BlocketTransmission = "manual" | "automatic" | "sequential";

export type BlocketDriveType = "fwd" | "rwd" | "awd";

export interface BlocketMileage {
  value: number;
  unit: "km" | "mi";
}

export interface BlocketCarCondition {
  mileage?: BlocketMileage;
  is_new_vehicle?: boolean;
}

export interface BlocketCarPowertrain {
  fuels?: BlocketFuel[];
  transmission?: BlocketTransmission;
  drive_type?: BlocketDriveType;
}

export interface BlocketCarCategoryFields {
  brand: string;
  model: string;
  model_year: number;
  body_type: string;
  registration_number?: string;
  vin?: string;
  color?: string;
  condition?: BlocketCarCondition;
  powertrain?: BlocketCarPowertrain;
}

export interface BlocketAdPayload {
  source_id: string;
  category_id: 1020;
  dealer_code?: string;
  body: string;
  price: Array<{ type: "list"; amount: number }>;
  image_urls: string[];
  visible?: boolean;
  category_fields: BlocketCarCategoryFields;
  // NOTE: title and contact are NOT allowed for category 1020 (registered vehicles)
  // They are auto-generated by Blocket from category_fields and the store profile.
}
